### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by behnood-eghbali** [oliaee/Githopper#2]
Avoid importing same modules multiple times in your code. No matter how many times you import them they get initialized only once.  **Code duplication is an anti-pattern.** It decreases the quality and readability of your code.**Try using DRY (Don't Repeat Yourself) principle to avoid code duplication.**
https://github.com/oliaee/Githopper/blob/a23213e5fecf9aac5296ae9ea81691e88fc8eb1f/Compile%20Ready%20codes/Githopper.py#L89-L97

**Comment by oliaee** [comment]
In order to compile multiple githopper components into a single file, I had to repeat import statements. I'll try to find a workaround to avoid code duplication.
for more info:
https://discourse.mcneel.com/t/tutorial-creating-a-grasshopper-component-with-the-python-ghpy-compiler/38552/3

**Comment by behnood-eghbali** [comment]
@oliaee There must be a better way to do this. ;) Thanks for the info.
