### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by behnood-eghbali** [oliaee/Githopper#3]
Avoid using numbers for naming classes in your code. It makes your code less readable. Try following naming rules 
 and conventions. **Python Naming Conventions:** https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html
https://github.com/oliaee/Githopper/blob/a23213e5fecf9aac5296ae9ea81691e88fc8eb1f/Compile%20Ready%20codes/Githopper.py#L9

**Comment by oliaee** [comment]
thank you for the great suggestion. I'll try use a better naming scheme for the next update.
