### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by behnood-eghbali** [oliaee/Githopper#4]
Avoid using too many classes and modules with the same functionality. Instead, reduce the lines of code and the file size.
**Try using best practices, clean code tips, refactoring techniques, design patterns and DRY principles to increase the readability, quality and efficiency of your code.**

**Comment by oliaee** [comment]
This code is written for the Grasshopper software and code repetition is due to the fact that grasshopper components cannot share or even access each others classes.
I appreciate your grasp of software design principles 👌
